CREATE TABLE mytable(
   id           INTEGER  NOT NULL PRIMARY KEY 
  ,Name         VARCHAR(59) NOT NULL
  ,Full_Address VARCHAR(47) NOT NULL
  ,Website      VARCHAR(34)
);
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (1,'Restaurant LaRoche','Hengelosestraat 200, 7521 AL Enschede','restaurantlaroche.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (2,'De Ouwe Compagnie','Walstraat 39, 7511 GG Enschede','deouwecompagnie.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (3,'Big Belly''s Tavern','Van Lochemstraat 230, 7511 PM Enschede','big-bellys.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (4,'burgerme Enschede','Willem Wilminkplein 27, 7511 PP Enschede','burgerme.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (5,'Blue Sakura','Oude Markt 21, 7511 GB Enschede','bluesakura.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (6,'Asaka','Zuiderhagen 53, 7511 GK Enschede','asaka.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (7,'Argentijns Steakhouse Grillmasters','Langestraat 54, 7511 HC Enschede','grillmasters.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (8,'Steakhouse Lutscher Alm B.V.','Lossersestraat 189, 7525 PE Enschede','lutscheralm.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (9,'Dutch premium grill @Home Enschede','Janninksweg 58, 7513 DL Enschede','dutchpg.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (10,'De Branderie','Hendrik Jan van Heekplein 35, 7511 HM Enschede','debranderie.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (11,'Ginza Sushi','Klanderij 50 A, 7511 HS Enschede','ginza-sushi.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (12,'Gastrobarbijrozendaal','Het Rozendaal 10, 7523 XG Enschede','gastrobarbijrozendaal.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (13,'Restaurant Hanninkshof','Usselerhofweg 5, 7548 RZ Enschede','hanninkshof.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (14,'puntoPASTA','Hendrik Jan van Heekplein 62, 7511 HN Enschede','puntopasta.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (15,'Lunchroom Het Rigtpunt','Rigtersbleek-Aalten 4, 7521 RB Enschede','lunchroomrigtpunt.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (16,'Heel Bijzonder Enschede','De Heurne 47, 7511 GZ Enschede','heelbijzonder.com');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (17,'Goodys','Marktstraat 2, 7511 GD Enschede','goodys.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (18,'Joop''s Broodjes','Deurningerstraat 57, 7514 BD Enschede','joopsbroodjes.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (19,'Oh my grill','Hengelosestraat 170, 7521 AK Enschede','ohmygrill.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (20,'Ana Doner V.O.F.','G.J. van Heekstraat 245, 7521 EE Enschede','anadoner.ultimatumapp.com');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (21,'Spaans Restaurant Los Sueños "mas que tapas" in Enschede','Walstraat 41, 7511 GG Enschede','lossuenos.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (22,'Bistro Dreams Enschede','Walstraat 5, 7511 GE Enschede','bistrodreams.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (23,'Restaurant Haifa','Gronausestraat 1241, 7534 AJ Enschede','haifaenschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (24,'Sensazia All-in restaurant','Colosseum 80, 7521 PT Enschede','sensazia.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (25,'Kosie Restaurant','Van Lochemstraat 226, 7511 PM Enschede','kosie-restaurant.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (26,'Mazza Libanees Restaurant','Walstraat 1, 7511 GE Enschede','restaurantmazza.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (27,'Restaurant De Tropen','Bolwerkstraat 9, 7511 GP Enschede','restaurantdetropen.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (28,'Le Mans EET-DRINK & GENIET','Brouwerijplein 18, 7523 MB Enschede','lemansenschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (29,'Verso Cucina Italiana ''d Intenzo','Deurningerstraat 11, 7514 BC Enschede','restaurantverso.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (30,'Restaurant Turquoise','Korte Haaksbergerstraat 3, 7511 JV Enschede','turquoise-enschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (31,'CopaCabana Steakhouse & Tapasrestaurant','Oude Markt 31, 7511 GB Enschede','copacabana-cafe.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (32,'Restaurant Het Middelpunt','Rembrandtlaan 56, 7545 ZL Enschede','middelpunt-enschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (33,'Restaurant Zeytin','Haaksbergerstraat 98, 7513 EA Enschede','restaurantzeytin.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (34,'De Kater','Oude Markt 5, 7511 GA Enschede','dekater.com');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (35,'Bistro en Wijnbar BRUUT (heropening op 17 september 2020)','Noorderhagen 42, 7511 EL Enschede','bistrobruut.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (36,'Habibi','Wethouder Beversstraat 185, 7543 BK Enschede','habibienschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (37,'Oaks Gastrobar','Stadsgravenstraat 47, 7511 EP Enschede','oaksgastrobar.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (38,'Ji-NOS','Oude Markt 28, 7511 GB Enschede',NULL);
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (39,'Restaurant Cozy','Marskant 34, 7551 BW Hengelo','restaurantcozy.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (40,'Sam Sam','Oude Markt 15, 7511 GA Enschede','samsam-enschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (41,'Eetcafé De Fusting','Hengelosestraat 281, 7521 AD Enschede','defusting.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (42,'Damascus restaurant','Noorderhagen 3, 7511 EJ Enschede','damascuseethuis.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (43,'Fabels','Oude Markt 4, 7511 GA Enschede','fabels-enschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (44,'Toons Snelbuffet','G.J. van Heekstraat 258, 7521 EL Enschede','toonssnelbuffet-enschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (45,'Frans op den Bult | Restaurant, Hotel, Zalen - Hengelo e.o.','Hengelosestraat 6, 7561 RT Deurningen','fransopdenbult.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (46,'Bardot Enschede','Langestraat 47c, 7511 HB Enschede','bardot.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (47,'De Pyramiden','Nieuwstraat 38, 7551 CZ Hengelo','pyramiden.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (48,'Turtles Pizza','Hengelosestraat 172, 7521 AK Enschede','turtlepizza.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (49,'Fletcher Hotel-Restaurant De Broeierd-Enschede','Hengelosestraat 725, 7521 PA Enschede','fletcherhotelenschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (50,'Restaurant Hisar','Burgemeester Jansenplein 50-54, 7551 ED Hengelo','restauranthisar.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (51,'Lovely Local','Walstraat 7, 7511 GE Enschede','lovelylocal.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (52,'Restaurant Joann','Nijverheidstraat 2, 7511 JM Enschede','restaurantjoann.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (53,'KFC','Kalanderstraat 2, 7511 HX Enschede','kfc.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (54,'Het Paradijs','Nicolaas Beetsstraat 48, 7514 CW Enschede','hetparadijs.com');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (55,'Japans Restaurant TAO','Deurningerstraat 17, 7514 BC Enschede','restauranttao.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (56,'''t Lansink (Hotel - Restaurant)','C.T. Storkstraat 18, 7553 AR Hengelo','hotellansink.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (57,'Carlina''s Latin Cuisine','Walstraat 69, 7511 GG Enschede','carlinas.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (58,'The Saloon','Walstraat 63, 7511 GG Enschede','the-saloon.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (59,'Restaurant de Basis','Walstraat 15-17, 7511 GE Enschede','terugnaardebasis.nu');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (60,'Eethuis Toros','Brouwerijplein 28, 7523 MB Enschede','eethuistoros.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (61,'De Eetkamer','De Bleek 19, 7622 LJ Borne','eetkamer-borne.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (62,'Foodbar BLUFF','Oude Markt 6, 7511 GA Enschede','bluff.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (63,'Thais Restaurant Aroy-D','Noorderhagen 20, 7511 EL Enschede','aroy-d.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (64,'Hu''s Garden','Oldenzaalsestraat 266, 7523 AG Enschede','husgarden.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (65,'Spice King India Enschede','Stadsgravenstraat 55, 7511 ER Enschede','spicekingindia.com');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (66,'Grieks Restaurant Rhodos','Korte Haaksbergerstraat 13, 7511 JV Enschede','makro.rest');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (67,'Argentijns restaurant poco mucho','Korte Haaksbergerstraat, 7511 JV Enschede','pocomucho-enschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (68,'Paddy''s','Oude Markt 12, 7511 GA Enschede','paddys.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (69,'Saray Ocakbasi','Deurningerstraat 91C, 7514 BE Enschede',NULL);
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (70,'Balkan Restaurant','Drienerstraat 29, 7551 HK Hengelo','restaurantbalkan.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (71,'Brasserie Kachel','Bentrotstraat 45, 7531 AA Enschede','brasseriekachel.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (72,'Restaurant Thessaloniki','Langestraat 52, 7511 HC Enschede','thessalonikienschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (73,'Sapori e Ricordi','Haverstraatpassage 21, 7511 ET Enschede','saporiericordi.com');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (74,'Grand Cafe De Steeg','Grotestraat 181-183, 7622 DD Borne','grandcafedesteeg.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (75,'Van der Valk Hotel Enschede','Zuiderval 140, 7543 EZ Enschede','vandervalkhotelenschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (76,'Sorrentino','Stadsgravenstraat 34, 36a, 7511 ES Enschede','sorrentino.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (77,'Fellini Enschede','Bolwerkstraat 2, 7511 GP Enschede','fellini.nu');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (78,'Nyonya Meneer Indonesisch Eethuis','Walstraat 9, 7511 GE Enschede','nyonyameneer.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (79,'Snackkar aan huis "Tukker food" betrouwbaar en betaalbaar','Waalstraat 50, 7523 RK Enschede','tukker-food.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (80,'Restaurant de Oude Apotheek','Teylersstraat 4, 7581 AH Losser','oude-apotheek.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (81,'Humphrey''s Restaurant Enschede','Oude Markt 3A, 7511 GA Enschede','humphreys.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (82,'Los Ponchos','Korte Haaksbergerstraat 2, 7511 JS Enschede','losponchos.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (83,'Yuzu Enschede','Van Loenshof 35, 7511 HE Enschede','yuzuenschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (84,'Masada','Wethouder Gerbertstraat 61, 7543 AW Enschede','masada.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (85,'Steakhouse El Gaucho','Zuiderhagen 16, 7511 GL Enschede','el-gaucho-enschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (86,'Eetcafé Bij Flip','Langestraat 58-60, 7511 HC Enschede','eetcafebijflip.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (87,'Vaperansa''s Soul Food','Hoge Bothofstraat 39A, 7514 ZA Enschede','vaperansa.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (88,'Moeke Enschede','Oude Markt 8, 7511 GA Enschede','moekeenschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (89,'Restaurant & Grand Café The Gallery Enschede','Hengelosestraat 500, 7521 AN Enschede','gallerycatering.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (90,'Cafetaria Sylvia','Rijnstraat 74, 7523 GH Enschede','sylvia-enschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (91,'Van Doorn en Doorn','Steenbeltweg 48, 7523 VZ Enschede','vandoornendoorn.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (92,'Pinto Thai','Korte Haaksbergerstraat 11, 7511 JV Enschede','pintothai.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (93,'Light of India','Emmastraat 189, 7513 BC Enschede','ecocentrumemma.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (94,'Happy Italy','Willem Wilminkplein 31, 7511 PP Enschede','happyitaly.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (95,'De Pauw','Deurningerstraat 217, 7522 CB Enschede',NULL);
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (96,'Bistro C''est Si Bon','Noorderhagen 54A, 7511 EM Enschede','cestsibon.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (97,'Mario''s en Mario''s Sweets','Hengelosestraat 184B, 7521 AK Enschede','marios-burgers.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (98,'Eetcafe ’t Raedthuys','Sint Maartenstraat 57, 7581 AK Losser','eetcaferaedthuys.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (99,'Restaurant De Stadsgracht','Stadsgravenstraat 57, 7511 ER Enschede','destadsgracht.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (100,'Restaurant ZIN','Noord Esmarkerrondweg 421-2, 7533 BL Enschede','restaurantzin.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (101,'Van der Poel','Oude Markt 23, 7511 GB Enschede','vanderpoelijs.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (102,'The green room','Beursstraat 44, 7551 HV Hengelo',NULL);
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (103,'Olympic','Korte Haaksbergerstraat 4, 7511 JS Enschede','grieksrestaurantenschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (104,'Bagels & Beans','Korte Hengelosestraat 33, 7511 JA Enschede','bagelsbeans.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (105,'Pulcinella B.V.','Deurningerstraat 91, 7514 BE Enschede','pizzeria-pulcinella.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (106,'Rosy''s','Van Loenshof 86, 7511 NK Enschede','rosysfood.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (107,'Twentse Bierbrouwerij','Haaksbergerstraat 51, 7554 PA Hengelo','twentsebierbrouwerijproeflokaal.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (108,'De Lunchkamer','Roomweg 75, 7523 BL Enschede','lunchkamer.com');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (109,'Kleinsman Eten en Drinken','Weerseloseweg 356, 7522 PT Enschede',NULL);
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (110,'Chinese Restaurant International','Boulevard 1945 322, 7511 AJ Enschede','chineesrestaurantenschede.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (111,'Restaurant Shalom - The Ribman','Willemstraat 54, 7551 DN Hengelo','shalom-hengelo.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (112,'Broasted Chicken','Kuipersdijk 5A, 7512 CA Enschede','broastedchicken.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (113,'Stravinsky eten · drinken · slapen','Burgemeester Jansenplein 20, 7551 ED Hengelo','stravinsky.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (114,'Tentje Teman²','Korte Haaksbergerstraat 46, 7511 JS Enschede','tentjeteman2.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (115,'HAOHAO','Langestraat 19, 7511 HA Enschede','wokhaohao.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (116,'Stichting Kookklup Lekker Eten','Spechtstraat 25, 7523 WJ Enschede',NULL);
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (117,'Restaurant De Broeierd','Hengelosestraat 725, 7521 PA Enschede','bistrodebroeierd.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (118,'JAMe Food Enschede','Willem Wilminkplein 27a, 7511 PP Enschede','jamefood.com');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (119,'Restaurant Fleur De Sel','Beckumerstraat 20, 7548 BG Enschede','restaurantfleurdesel.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (120,'Shivani''s Surinaams Eethuis','Lipperkerkstraat 33, 7511 CT Enschede','shivanis.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (121,'The Bombay Spice','Wemenstraat 59, 7551 EW Hengelo','bombayspice.nl');
INSERT INTO mytable(id,Name,Full_Address,Website) VALUES (122,'La Place','Raadhuisstraat 12, 7511 HK Enschede','laplace.com');
